### ISSUE TITLE
[PE-D][Tester E] Result display is cut off at the right edge on launch

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#115]
## Description

The right edge of the results display is cut off on launch.

![image.png](https://raw.githubusercontent.com/yisiox/ped/main/files/5410c947-4aa4-4af4-9007-922f99491c7d.png)

## Steps to reproduce

Launch the app at 1920 x 1080 resolution.

## Reason for severity

Minor cosmetic bug.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: yisiox/ped#1

**Comment by ashleygoh1** [comment]
invalid, not a bug
