### ISSUE TITLE
[PE-D][Tester D] UI Cutoff Issue for Long Input Fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#128]
# Details
UI Cutoff for ALL fields within `add` command. Even notes, but the cutoff is significantly higher for notes which makes it unrealistic for `notes` specifically.  

# Steps to Reproduce
add n/[SOME INCREDIBLY LONG NAME HERE] ... (same for all fields)

# Example

![error_2.png](https://raw.githubusercontent.com/maze508/ped/main/files/fb0add9b-73bc-427c-a220-ed651a1e0f3f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: maze508/ped#6

**Comment by ashleygoh1** [comment]
not a bug, not allowed to fix, feature flaw, can be future enhancement
