### ISSUE TITLE
[PE-D][Tester A] Feature Flaw: Find Feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#151]
This is recorded as a feature flaw and not a functionality bug because as far as I can tell the command works as the UG describes. 
The flaw in the way the current command works is that it is supposed to help the users find a contact easily, yet it only updates the View Panel and not the List of Contacts.

The image below shows that my `find A` resulted in "1 person listed!". However the list of contacts still shows the full list. 

![image.png](https://raw.githubusercontent.com/BryanL2303/ped/main/files/f95cdc41-589c-4a25-b8b1-9ef0ad497b77.png)

This means that in the scenarios where my find results in multiple contacts being returned, the user will have to manually scroll through the entire View Panel to check if what they are looking for is in the list. This violates the constraints of the tp to allow users to work faster through their keyboards and the CLI.

I would personally advice to maybe also update the list of contacts after the find function? Since each contact takes up much less space on that side of the screen it will at least be faster for the user to scroll through it.

At the end I indicated this as low severity since the user could simply type in a better search term to get exactly what they might be looking for. While it has the potential to get annoying it can also be worked around relatively easily.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: BryanL2303/ped#4

**Comment by ashleygoh1** [comment]
invalid, not a bug, our idea was to have the find function update the view panel not the existing list panel
