### ISSUE TITLE
[PE-D][Tester E] Application fails silently if edited addressbook.json is invalid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#154]
## Description

If the user edits `addressbook.json` and results in an invalid entry, on launch the application launches without any error message, so the user is unaware that something went wrong.

## Expected behavior

Warn the user, or let the user know that the data will be erased.

## Actual behavior

The application launches, and the list of applications is empty. On exit, it overrides the old data file.

## Steps to reproduce

For example, change `salary` to have value `"-1"` under `addressbook.json`.

## Reason for severity

The user may be confused as to why data loss occurred.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yisiox/ped#11

**Comment by ashleygoh1** [comment]
invalid, not a bug, already mention in UG
