### ISSUE TITLE
[PE-D][Tester D]  Misleading Naming Convention for jd (Job Description) Field

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#171]
# Details

Current Keyword `jd` represents job description which contrasts what is shown in the UG. Perhaps a more suitable keyword name would be `jt` which represents job title instead

![img_7.PNG](https://raw.githubusercontent.com/maze508/ped/main/files/7ec1bd0f-3389-4eae-8101-f708ded4d97e.PNG)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: maze508/ped#17

**Comment by ashleygoh1** [comment]
invalid, not a bug
