### ISSUE TITLE
[PE-D][Tester E] Unable to search by multiple fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#182]
## Description

The application allows searching by company name, interview date and specific tags, but lacks the functionality to search by address, job title/description, internship duration and salary.

## Reason for severity

Being able to search by these fields is a likely feature that the user would want.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yisiox/ped#23

**Comment by ashleygoh1** [comment]
not a bug, possible future enhancement
