### ISSUE TITLE
[PE-D][Tester E] Searching features are unintuitive and complex

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-1/tp#183]
## Description

In essence, `find`, `reminder` and `filter` perform the same function, just that they are searching by different fields. Perhaps it may be easier for the user to only remember one `find` command, but can specify using prefixes which specific fields they want to search by.

## Reason for severity

It is an inconvenience to the user to remember different syntax to be able to search, and only be able to search by one field at a time, limiting the value that the application provides to the user.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: yisiox/ped#24

**Comment by ashleygoh1** [comment]
not a bug, possible future enhancement
